{
 "title": "Traffic Teams (psql)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "src",
    "label": "Origin (source)",
    "query": "SELECT DISTINCT src FROM vpn_traffic"
   },
   {
    "name": "dst",
    "label": "Destination",
    "query": "SELECT DISTINCT dst FROM vpn_traffic"
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "SELECT DISTINCT proto FROM vpn_traffic"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "SELECT DISTINCT port FROM vpn_traffic"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(src_bytes) / ($__interval_ms / 1000) AS \"request traffic\",\n  sum(dst_bytes) / ($__interval_ms / 1000) AS \"response traffic\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\n  AND src IN ($src)\n  AND dst IN ($dst)\n  AND proto IN ($proto) AND port IN ($port)\nGROUP BY \"time\"\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Traffic per port (within timerange)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  max(time) AS \"time\",\n  CONCAT(proto, ' ', CASE WHEN port = -1 THEN '(other)' ELSE CONCAT(':', port) END) AS \"title\",\n  sum(src_bytes + dst_bytes) AS \"bytes\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\n  AND src IN ($src)\n  AND dst IN ($dst)\n  AND proto IN ($proto)\n  AND port IN ($port)\nGROUP BY proto, port\nORDER BY proto, port"
    }
   ]
  },
  {
   "title": "Bandwidth per Origin Team",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  src,\n  sum(src_bytes + dst_bytes) / ($__interval_ms / 1000) AS \"traffic\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\n  AND src IN ($src)\n  AND dst IN ($dst)\n  AND proto IN ($proto) AND port in ($port)\nGROUP BY \"time\", src\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Bandwidth per Destination Team",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  dst,\n  sum(src_bytes + dst_bytes) / ($__interval_ms / 1000) AS \"traffic\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\n  AND src IN ($src)\n  AND dst IN ($dst)\n  AND proto IN ($proto) AND port in ($port)\nGROUP BY \"time\", dst\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "# connections" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(open_connections) / count(DISTINCT \"time\") AS \"open connections\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\n  AND src IN ($src)\n  AND dst IN ($dst)\n  AND proto IN ($proto) AND port in ($port)\nGROUP BY \"time\"\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(connection_count) / ($__interval_ms / 1000) AS \"connections\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\n  AND src IN ($src)\n  AND dst IN ($dst)\n  AND proto IN ($proto) AND port IN ($port)\nGROUP BY \"time\"\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Average Connection Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "# connections" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(connection_times) / sum(connection_count) AS \"connection time\"\nFROM vpn_traffic\nWHERE\n  $__timeFilter(\"time\")\n  AND src IN ($src)\n  AND dst IN ($dst)\n  AND proto IN ($proto) AND port in ($port)\nGROUP BY \"time\"\nORDER BY \"time\""
    }
   ]
  }
 ]
}